name: Rannabutt Workflows
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  My_first_workfows:
   name: my first job
   runs-on: self hosted
   steps:
    - name: Jai IT wale baba ki
     env:
         My_VAR: Hi there! My name is.
         First_Name: MK
         Message: I love AI
     run:|
        run: |
           echo $My_VAR $First_Name $Message

